### ISSUE TITLE
MessengerProfile doesn't support domain whitelisting

### ISSUE THREAD

**Issue by danfairs** [rehabstudio/fbmessenger#11]
I think this is another recent-ish feature that it would be good to support:

  https://developers.facebook.com/docs/messenger-platform/messenger-profile/domain-whitelisting

I'm happy to do the work to add this, but it probably won't be in the next few days (vacations beckon!)

**Comment by noamkush** [comment]
There's MessengerClient.update_whitelisted_domains and remove_whitelisted_domains.

**Comment by danfairs** [comment]
Huh - I didn't see that! Thanks. I went looking for it in the main messenger profile settings.

**Comment by rickydunlop** [comment]
Might be worth adding it to the documentation
