### ISSUE TITLE
Support for messaging_type property

### ISSUE THREAD

**Issue by dzbrozek** [rehabstudio/fbmessenger#15]
Any plans for adding the `messaging_type` property?

https://developers.facebook.com/docs/messenger-platform/send-messages#messaging_types

**Comment by rickydunlop** [comment]
Hey, yeah it will need to be added at some point as it's a breaking change.
I'm quite busy on other projects but will try and get it added in the next few weeks. 

Or, if you want to send a PR it would be very much appreciated :)

**Comment by rickydunlop** [comment]
Closed by #18
