### ISSUE TITLE
Django integration

### ISSUE THREAD

**Issue by sgaseretto** [rehabstudio/fbmessenger#22]
I have a django project and I will like to build a chatbot for it, but instead of running a different flask server i would like to build a new app inside the project with the bot functionality, any idea of how to do this?

**Comment by rickydunlop** [comment]
Yeah, it should be trivial to do this, you just need to add a route to your Django app that listens for the webhooks. 

If you look at the [example](https://github.com/rehabstudio/fbmessenger/blob/master/example/main.py#L150), all it's doing is listening for any GET/POST requests that come from FB and then it passes these to the Messenger instance.
