### ISSUE TITLE
Sending multiple text responses

### ISSUE THREAD

**Issue by saivisal1** [rehabstudio/fbmessenger#31]
Hi, I need to send the reply back to facebook as 2 different messages. How can i handle this?

`response = Text(text='Sorry, I am not able to answer for your queries right now.')`

I need **Sorry** and **I am not able to answer for your queries right now.** as two different messages. 

Please help.

**Comment by rickydunlop** [comment]
You can call `messenger.send()` twice in your handler. 

See https://github.com/rehabstudio/fbmessenger#text

You might want to put a slight delay between sending each message so it looks more natural, 
for example, you could do this

```python
import time
time.sleep(1)
```

**Comment by saivisal1** [comment]
Thanks that works :)
