### ISSUE TITLE
Use sender_id instead of entry (full message)

### ISSUE THREAD

**Issue by wittfabian** [rehabstudio/fbmessenger#52]
We should use the sender_id instead of the full message. It's easier if someone uses the library not only to respond to messages.

Example:
https://github.com/rehabstudio/fbmessenger/blob/master/fbmessenger/__init__.py#L45

```
def get_user_data(self, entry, fields=None, timeout=None):
```

**Comment by wittfabian** [comment]
Pull request is ready, waiting for #55

**Comment by wittfabian** [comment]
Needs discussion. @rickydunlop

**Comment by rickydunlop** [comment]
Yeah i'm happy to go with this, it would need a major version bump as it's a breaking change

**Comment by wittfabian** [comment]
Ok. We should provide the current version as 5.6.1
