### ISSUE TITLE
Sending a message to a specific user by ID

### ISSUE THREAD

**Issue by Stanwarr** [rehabstudio/fbmessenger#60]
Would you like assistance or advice?
Assistance.
Issue description
I can't seem to be able to send a message to a specific user after getting his ID
Steps to reproduce
I get the recipient_id through `sender=self.get_user_id()`
Then why I try to use `self.send({'text': "msg"}, sender, 'RESPONSE')` it fails with the error:
`ValueError: '2595091087229339' is not a valid 'messaging_type'`
It seems like it's handling the variable sender as if it's the messaging_type not recipient_id 
Any idea what am I doing wrong?

* fbmessenger version: 6.0.0 / master@commit
* python version: 3.7.1

**Comment by wittfabian** [comment]
`MessengerClient` or `BaseMessenger`

**Comment by Stanwarr** [comment]
Solved. Thanks a lot.
