### ISSUE TITLE
Answer concurrent messages

### ISSUE THREAD

**Issue by giulio-cirnigliaro** [rehabstudio/fbmessenger#61]
Hi everyone, first of all thank you in advance for your patience. I have a question: I noticed that using standard Flask configuration (as in the example), the library processes one message at a time. Therefore, I changed Flask WSGI server to gevent, to handle multiple concurrent connections. However, if two users send concurrent messages, the answers seem to be randomly mixing up. I noticed that `send` method of `BaseMessenger` class uses `last_message`, which doesn't seem to be thread-safe. Therefore, in the class extending `BaseMessenger` class, I implemented some sort of override of the `send` method like this:

```
    def raw_send(self, recipient_id, message_data, messaging_type='RESPONSE', tag=None):
        self.client.send(payload=self.build_message_template(message_data), 
                         entry={"sender": {"id": recipient_id}},
                         messaging_type=messaging_type,
                         tag=tag)
```
Did I do the right thing? Is there a way to use the library with concurrent requests? At the moment I am using fbmessenger 5.3.2. I hope my question isn't stupid. Thank you again.

**Comment by rickydunlop** [comment]
Hey, yeah this is totally fine, the `last_message` property should probably be removed to be honest. 
This library was ported from a node module I created and I removed the "last message" related code from it a long time ago due to the exact same problem.

**Comment by giulio-cirnigliaro** [comment]
Ok, thank you very much!
