### ISSUE TITLE
Support for `default_action` on `Element`

### ISSUE THREAD

**Issue by danfairs** [rehabstudio/fbmessenger#8]
`Element` currently does not support the `default_action` key, as per:

https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template

We need this, so I'll do the work and tests and open a PR, if that's OK - unless someone else is working on this?

**Comment by rickydunlop** [comment]
Hi Dan, yeah please go ahead. I don't work for rehabstudio anymore so I will see if @grieve can give me access to this repo to allow me to release builds etc
